version: '3.8'

services:
  app:
    image: node:17-alpine
    command: sh -c "yarn && yarn dev"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - .docker/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
