version: '3.8'

services:
  app:
    container_name: app
    image: node:17-alpine
    command: sh -c "
      npm install -g pnpm
      && pnpm install --frozen-lockfile -r
      && pnpm db:setup
      && pnpm dev"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
      - ${PNPM_STORE_DIR}:/app/.pnpm-store
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - .docker/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
